name: Deploy my Angular App
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build angular app
        run: |
          echo "Hello world"
          npm install
      - name: Deploy
      - working-directory: dist
        run: ls      